/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controllers.Bike;
import controllers.Car;
import controllers.CtrlVehicles;
import controllers.Truck;
import controllers.User;
import controllers.Vehicles;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FrmChofer extends javax.swing.JFrame {

     private User loginUser;
    private boolean edited;
    private ArrayList<Vehicles>data;
    private boolean change = false;

     public void setLoginUser(User user) {
        this.loginUser = user;
    }
   
    public FrmChofer() {
        initComponents();
        
         DefaultTableModel model = new DefaultTableModel(){
          public boolean isCellEditable(int row, int column) {
                return false;
            }
       };
        model.addColumn("Id");
        model.addColumn("Matricula");
        model.addColumn("Capacidad");
        model.addColumn("Tipo");
        
        CtrlVehicles ctrl = new CtrlVehicles();
        ArrayList<Vehicles> arrayVehicles = ctrl.getVehicles();
        this.data = ctrl.getVehicles();
        
        Vehicles veh = null;
        String type = null;
        
         for (int i = 0; i < arrayVehicles.size(); i++) {
            veh = arrayVehicles.get(i);
             if (veh instanceof Car) {
                type = "Carro";
            } else if (veh instanceof Truck) {
                type = "Camion";
            }else{
                type = "Motor";
            }
             
            model.addRow(new Object[]{veh.getId(), veh.getMatricle(), veh.getCapacity(),  type});
        }
         
         tblVehicles.setModel(model);
        
        tblVehicles.setFont(new Font("Tahoma", Font.PLAIN, 14));
        tblVehicles.setRowHeight(30);
        
        int[] arrCol = {40,260,100,100};      
         
         
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textChofer = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehicles = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textMatri = new javax.swing.JTextField();
        textCapacity = new javax.swing.JTextField();
        cmbType = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Vehículos :");

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N
        jLabel2.setText("Chofer :");

        textChofer.setEditable(false);
        textChofer.setBackground(new java.awt.Color(102, 102, 102));

        tblVehicles.setBackground(new java.awt.Color(204, 204, 204));
        tblVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Matrícula", "Capacidad", "Tipo de Vehículo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVehicles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVehiclesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVehicles);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Matrícula :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Capacidad :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tipo de Vehículo :");

        textMatri.setBackground(new java.awt.Color(204, 204, 204));

        textCapacity.setBackground(new java.awt.Color(204, 204, 204));
        textCapacity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textCapacityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textCapacityFocusLost(evt);
            }
        });
        textCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCapacityActionPerformed(evt);
            }
        });
        textCapacity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textCapacityKeyPressed(evt);
            }
        });

        cmbType.setBackground(new java.awt.Color(204, 204, 204));
        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Camión", "Motor" }));

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setFont(btnDelete.getFont().deriveFont(btnDelete.getFont().getSize()+2f));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/delete.png"))); // NOI18N
        btnDelete.setText("Eliminar");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        btnNew.setBackground(new java.awt.Color(204, 204, 204));
        btnNew.setFont(btnNew.getFont().deriveFont(btnNew.getFont().getSize()+2f));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/add.png"))); // NOI18N
        btnNew.setText("Agregar");
        btnNew.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setFont(btnSave.getFont().deriveFont(btnSave.getFont().getSize()+2f));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/disk.png"))); // NOI18N
        btnSave.setText("Guardar");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(204, 204, 204));
        btnClose.setFont(btnClose.getFont().deriveFont(btnClose.getFont().getSize()+2f));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/door_in.png"))); // NOI18N
        btnClose.setText("Cerrar");
        btnClose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(204, 204, 204));
        btnEdit.setFont(btnEdit.getFont().deriveFont(btnEdit.getFont().getSize()+2f));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/pencil.png"))); // NOI18N
        btnEdit.setText("Modificar");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(textMatri, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textCapacity, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNew)
                        .addGap(35, 35, 35)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(textChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textMatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete)
                    .addComponent(btnNew)
                    .addComponent(btnEdit))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave)
                    .addComponent(btnClose))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private boolean isValidCapacity(String capacity) {
    try {
        int value = Integer.parseInt(capacity);
        if (value < Integer.MIN_VALUE || value > Integer.MAX_VALUE) {
            JOptionPane.showMessageDialog(null, "Estas loco?, ese numero es gigantezco ", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "La capacidad debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
}


    
    private void textCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCapacityActionPerformed

    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked
        
        
        if ( !textMatri.getText().equals("") && !textCapacity.getText().equals("") ) {
                    if (isValidCapacity(textCapacity.getText())) {

          
            DefaultTableModel model = (DefaultTableModel)tblVehicles.getModel();        
            String type = null;
            int id = model.getRowCount() + 1;
            switch (cmbType.getSelectedIndex()) { 
                case 0:
                    type="Carro";
                    break;
                case 1:
                    type="Camion";
                    break;
                case 2:
                    type="Motor";
                    break;

            }
             model.addRow(new Object[]{id, textMatri.getText(), textCapacity.getText(), type});
            tblVehicles.setModel(model);
            textMatri.setText("");
            textCapacity.setText("");
            cmbType.setSelectedIndex(0);
                    }
        }        // TODO add your handling code here:
        change = true;
    }//GEN-LAST:event_btnNewMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
         int row = tblVehicles.getSelectedRow();
        if (row >= 0) {
            DefaultTableModel model = (DefaultTableModel)tblVehicles.getModel();
            model.setValueAt(textMatri.getText().trim(), row, 1);
            model.setValueAt(textCapacity.getText().trim(), row, 2);
         
            String type = null;
            switch (cmbType.getSelectedIndex()) {
                case 0:
                    type="Carro";
                    break;
                case 1:
                    type="Camion";
                    break;
                case 2:
                    type="Motor";
                    break;
                
            }
            model.setValueAt(type, row, 3);
        }         // TODO add your handling code here:
        change = true;
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        int row = tblVehicles.getSelectedRow();
        
        if (row >= 0) {
            DefaultTableModel model = (DefaultTableModel)tblVehicles.getModel();
            
            String id = model.getValueAt(row, 0).toString();
            
           
        
                int resp = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar este vehículo", "Eliminar vehículo", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if(resp == 0) {
                    model.removeRow(row);
                    
                    textMatri.setText("");
                    textCapacity.setText("");
                    cmbType.setSelectedIndex(0);                    
                }
            
             
        
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar el vehículo que desea eliminar", "Eliminar Vehículo", JOptionPane.INFORMATION_MESSAGE);            
        }         // TODO add your handling code here:
        change = true;
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        if(change){
         int confirm =  JOptionPane.showConfirmDialog(null, "Hay cambios sin guardar, desea salir igualmente?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
         if(confirm == 0){
             FrmLogin frmlogin = new FrmLogin();
        frmlogin.setVisible(true);
        frmlogin.setLocationRelativeTo(null);                                                        
        
        this.dispose();       
         }
       }  else{FrmLogin frmlogin = new FrmLogin();
        frmlogin.setVisible(true);
        frmlogin.setLocationRelativeTo(null);                                                        
        
        this.dispose(); }

               // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
          DefaultTableModel model = (DefaultTableModel)tblVehicles.getModel();
        ArrayList<Vehicles> arrayVehicles = new ArrayList<>();

        for (int i=0; i<model.getRowCount(); i++) {                
            switch (model.getValueAt(i, 3).toString()) {
                case "Carro":
                    arrayVehicles.add(new Car(model.getValueAt(i, 0).toString(), model.getValueAt(i, 1).toString(), Integer.parseInt(model.getValueAt(i, 2).toString())));
                    break;
                case "Camion":
                    arrayVehicles.add(new Truck(model.getValueAt(i, 0).toString(), model.getValueAt(i, 1).toString(), Integer.parseInt(model.getValueAt(i, 2).toString())));
                    break;
                case "Motor":
                     
                    arrayVehicles.add(new Bike(model.getValueAt(i, 0).toString(), model.getValueAt(i, 1).toString(), Integer.parseInt(model.getValueAt(i, 2).toString())));
                    break;
                    
                    
                
            }
            
        }
        
        CtrlVehicles ctrl = new CtrlVehicles();
        boolean isSaved = ctrl.saveVehicles(arrayVehicles);
        
        if ( isSaved ) {
            JOptionPane.showMessageDialog(null, "Información guardada con éxito", "Garajes", JOptionPane.INFORMATION_MESSAGE);  
            
   
            
            
        } else {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al guardar los datos", "Garajes", JOptionPane.ERROR_MESSAGE);                        
        }         // TODO add your handling code here:
        change = false;
    }//GEN-LAST:event_btnSaveMouseClicked

    private void tblVehiclesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVehiclesMouseClicked
        int row = tblVehicles.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tblVehicles.getModel();
        textMatri.setText(model.getValueAt(row, 1).toString());
        textCapacity.setText(model.getValueAt(row, 2).toString());
        cmbType.setSelectedItem(model.getValueAt(row, 3).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_tblVehiclesMouseClicked

    private void textCapacityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCapacityKeyPressed
       
      
           // TODO add your handling code here:
    }//GEN-LAST:event_textCapacityKeyPressed

    private void textCapacityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCapacityFocusGained
                // TODO add your handling code here:
    }//GEN-LAST:event_textCapacityFocusGained

    private void textCapacityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCapacityFocusLost
         
            // TODO add your handling code here:
    }//GEN-LAST:event_textCapacityFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmChofer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVehicles;
    private javax.swing.JTextField textCapacity;
    public static javax.swing.JTextField textChofer;
    private javax.swing.JTextField textMatri;
    // End of variables declaration//GEN-END:variables
}
