/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controllers.CtrlStore;
import controllers.ForestalBiomassStore;
import controllers.ResidualBiomassStore;
import controllers.Store;
import controllers.User;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FrmGrocer extends javax.swing.JFrame {
    
    private User loginUser;
    private boolean edited;
    private ArrayList<Store>data;
   

   
   
    public void setLoginUser(User user) {
        this.loginUser = user;
    }

    /**
     * Creates new form ChoferView
     */
    public FrmGrocer() {
        initComponents();
        
        DefaultTableModel model = new DefaultTableModel(){
          public boolean isCellEditable(int row, int column) {
                return false;
            }
       };
        model.addColumn("Id");
        model.addColumn("Nombre");
        model.addColumn("Capacidad");
        model.addColumn("Personal");
        model.addColumn("Tipo");
        
        CtrlStore ctrl = new CtrlStore();
        ArrayList<Store> arrayStore = ctrl.getStores();
        this.data = ctrl.getStores();

        Store stor = null;
        String type = null;
        
         for (int i = 0; i < arrayStore.size(); i++) {
            stor = arrayStore.get(i);
             if (stor instanceof ResidualBiomassStore) {
                type = "Biomasa Residual";
            } else if (stor instanceof ForestalBiomassStore) {
                type = "Biomasa Forestal";
            }
            

            model.addRow(new Object[]{stor.getId(), stor.getName(), stor.getCapacity(), stor.getPersonal(), type});
        }
         
         tblStores.setModel(model);
        
        tblStores.setFont(new Font("Tahoma", Font.PLAIN, 14));
        tblStores.setRowHeight(30);
        
        int[] arrCol = {40,260,100,100,100};        
        
          
    }
        
        
    
        
        
     
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblGrocer = new javax.swing.JLabel();
        textGrocer = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        textCapacity = new javax.swing.JTextField();
        textPersonal = new javax.swing.JTextField();
        cmbType = new javax.swing.JComboBox<>();
        btnNew = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Almacenes");

        lblGrocer.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N
        lblGrocer.setText("Almacenero :");

        textGrocer.setEditable(false);
        textGrocer.setBackground(new java.awt.Color(102, 102, 102));
        textGrocer.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        textGrocer.setForeground(new java.awt.Color(255, 255, 255));
        textGrocer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textGrocer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textGrocerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addComponent(lblGrocer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textGrocer, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrocer)
                    .addComponent(textGrocer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tblStores.setBackground(new java.awt.Color(204, 204, 204));
        tblStores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Capacidad", "Personal", "Tipo De almacen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStores);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nombre :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Capacidad :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Personal :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tipo de almacen :");

        textName.setBackground(new java.awt.Color(204, 204, 204));
        textName.setFont(textName.getFont().deriveFont(textName.getFont().getSize()+3f));
        textName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });

        textCapacity.setBackground(new java.awt.Color(204, 204, 204));
        textCapacity.setFont(textCapacity.getFont().deriveFont(textCapacity.getFont().getSize()+3f));
        textCapacity.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        textPersonal.setBackground(new java.awt.Color(204, 204, 204));
        textPersonal.setFont(textPersonal.getFont().deriveFont(textPersonal.getFont().getSize()+3f));
        textPersonal.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        cmbType.setBackground(new java.awt.Color(204, 204, 204));
        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biomasa Forestal", "Biomasa Residual" }));
        cmbType.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        btnNew.setBackground(new java.awt.Color(204, 204, 204));
        btnNew.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/add.png"))); // NOI18N
        btnNew.setText("Agregar");
        btnNew.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
        });
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/delete.png"))); // NOI18N
        btnDelete.setText("Eliminar");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(204, 204, 204));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/pencil.png"))); // NOI18N
        btnEdit.setText("Modificar");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdmin.setBackground(new java.awt.Color(204, 204, 204));
        btnAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/Name Tag.png"))); // NOI18N
        btnAdmin.setText("Administrar");
        btnAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminMouseClicked(evt);
            }
        });
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/disk.png"))); // NOI18N
        btnSave.setText("Guardar");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(204, 204, 204));
        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/door_in.png"))); // NOI18N
        btnClose.setText("Cerrar");
        btnClose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textName)
                        .addComponent(textCapacity)
                        .addComponent(textPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isValidCapacity(String capacity, String personal) {
    try {
        int value = Integer.parseInt(capacity);
        if (value < Integer.MIN_VALUE || value > Integer.MAX_VALUE) {
            JOptionPane.showMessageDialog(null, "Estas loco?, el numero es gigantezco " , "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        int personalValue = Integer.parseInt(personal);
        if (personalValue < Integer.MIN_VALUE || personalValue > Integer.MAX_VALUE) {
            JOptionPane.showMessageDialog(null, "Estas loco?, el numero es gigantezco " , "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "La capacidad y el personal deben ser números", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
}
     public boolean isValidCapacity(String capacity) {
    try {
        Integer.parseInt(capacity);
        return true;
    } catch (NumberFormatException e) {
        return false;
    }
}
    
    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminActionPerformed

    private void textGrocerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textGrocerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textGrocerActionPerformed

    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked
         if ( !textName.getText().equals("") && !textCapacity.getText().equals("") && !textPersonal.getText().equals("" ) ) {
                    if (isValidCapacity(textCapacity.getText(), textPersonal.getText())) {
                        
            DefaultTableModel model = (DefaultTableModel)tblStores.getModel();        
            String type = null;
            String name = textName.getText();
            boolean exists = false;
            for (int i = 0; i < model.getRowCount(); i++) {
                if (model.getValueAt(i, 1).toString().equals(name)) {
                    exists = true;
                    break;
                }
            }
            int id = model.getRowCount() + 1;
            if(!exists){
            switch (cmbType.getSelectedIndex()) { 
                case 0:
                    type="Biomasa Forestal";
                    break;
                case 1:
                    type="Biomasa Residual";
                    break;

            }
             model.addRow(new Object[]{id, textName.getText(), textCapacity.getText(), textPersonal.getText(), type});
            tblStores.setModel(model);
            textName.setText("");
            textCapacity.setText("");
            textPersonal.setText("");
            cmbType.setSelectedIndex(0);
        }else{
            JOptionPane.showMessageDialog(null, "El almacen ya existe");
        }
        }
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_btnNewMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        int row = tblStores.getSelectedRow();
        if (row >= 0) {
            DefaultTableModel model = (DefaultTableModel)tblStores.getModel();
            model.setValueAt(textName.getText().trim(), row, 1);
            model.setValueAt(textCapacity.getText().trim(), row, 2);
            model.setValueAt(textPersonal.getText().trim(), row, 3);
            String type = null;
            switch (cmbType.getSelectedIndex()) {
                case 0:
                    type="Biomasa Forestal";
                    break;
                case 1:
                    type="Biomasa Residual";
                    break;
                
            }
            model.setValueAt(type, row, 4);
        } 
                // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
       int row = tblStores.getSelectedRow();
        
        if (row >= 0) {
            DefaultTableModel model = (DefaultTableModel)tblStores.getModel();
            
            String id = model.getValueAt(row, 0).toString();
            
           
        
                int resp = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar este almacen", "Eliminar almacen", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if(resp == 0) {
                    model.removeRow(row);
                    
                    textName.setText("");
                    textCapacity.setText("");
                    textPersonal.setText("");
                    cmbType.setSelectedIndex(0);                    
                }
            
             
        
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar el almacen que desea eliminar", "Eliminar Almacen", JOptionPane.INFORMATION_MESSAGE);            
        } 

// TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        FrmLogin frmlogin = new FrmLogin();
        frmlogin.setVisible(true);
        frmlogin.setLocationRelativeTo(null);                                                        
        
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
           DefaultTableModel model = (DefaultTableModel)tblStores.getModel();
        ArrayList<Store> arrayStores = new ArrayList<>();

        for (int i=0; i<model.getRowCount(); i++) {                
            switch (model.getValueAt(i, 4).toString()) {
                case "Biomasa Forestal":
                    arrayStores.add(new ForestalBiomassStore(model.getValueAt(i, 0).toString(), model.getValueAt(i, 1).toString(), Integer.parseInt(model.getValueAt(i, 2).toString()), Integer.parseInt(model.getValueAt(i, 3).toString())));
                    break;
                case "Biomasa Residual":
                    arrayStores.add(new ResidualBiomassStore(model.getValueAt(i, 0).toString(), model.getValueAt(i, 1).toString(), Integer.parseInt(model.getValueAt(i, 2).toString()), Integer.parseInt(model.getValueAt(i, 3).toString())));
                    break;
                
            }
            
        }
        
        CtrlStore ctrl = new CtrlStore();
        boolean isSaved = ctrl.saveStores(arrayStores);
        
        if ( isSaved ) {
            JOptionPane.showMessageDialog(null, "Información guardada con éxito", "Almacenes", JOptionPane.INFORMATION_MESSAGE);  
            
   
            
            
        } else {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al guardar los datos", "Almacenes", JOptionPane.ERROR_MESSAGE);                        
        } 
// TODO add your handling code here:
    }//GEN-LAST:event_btnSaveMouseClicked

    private void tblStoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStoresMouseClicked
        int row = tblStores.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tblStores.getModel();
        textName.setText(model.getValueAt(row, 1).toString());
        textCapacity.setText(model.getValueAt(row, 2).toString());
        textPersonal.setText(model.getValueAt(row, 3).toString()); 
        cmbType.setSelectedItem(model.getValueAt(row, 4).toString());
            
               // TODO add your handling code here:
    }//GEN-LAST:event_tblStoresMouseClicked

    private void btnAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseClicked
         if (tblStores.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "No hay filas en la tabla", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int row = tblStores.getSelectedRow();
    DefaultTableModel model = (DefaultTableModel)tblStores.getModel();
    String tipoAlmacen = model.getValueAt(row, 4).toString();
    String nombreAlmacen = model.getValueAt(row, 1).toString();// asumiendo que la columna 1 es el tipo de almacén
    Store store = getStoreFromRow(row, model);
    FrmBiomass frmBiomass = new FrmBiomass();
        FrmBiomass.lblStoreName.setText(nombreAlmacen);

    if (tipoAlmacen.equals("Biomasa Forestal")) {
        frmBiomass.lblStore.setText("Almacén de Biomasa Forestal");
        frmBiomass.lblStore.setVisible(true);
        frmBiomass.setLocationRelativeTo(null);
    } else if (tipoAlmacen.equals("Biomasa Residual")) {
        frmBiomass.lblStore.setText("Almacén de Biomasa Residual");
        frmBiomass.lblStore.setVisible(true);
        frmBiomass.setLocationRelativeTo(null);
    }
    
    this.setState(JFrame.ICONIFIED);
    frmBiomass.addWindowListener(new WindowAdapter() {
       
        public void windowClosed(WindowEvent e) {
            // Restaurar la ventana de almacen
            FrmGrocer.this.setState(JFrame.NORMAL);
        }
    });

    frmBiomass.setVisible(true);
     /// TODO add your handling code here:
    }//GEN-LAST:event_btnAdminMouseClicked

    private Store getStoreFromRow(int row, DefaultTableModel model) {
        // Obtener el almacén seleccionado desde la tabla
        String id = model.getValueAt(row, 0).toString();
        String name = model.getValueAt(row, 1).toString();
        int capacity = Integer.parseInt(model.getValueAt(row, 2).toString());
        int personal = Integer.parseInt(model.getValueAt(row, 3).toString());
        String type = model.getValueAt(row, 4).toString();
    
        Store store;
        if (type.equals("Biomasa Forestal")) {
            store = new ForestalBiomassStore(id, name, capacity, personal);
        } else if (type.equals("Biomasa Residual")) {
            store = new ResidualBiomassStore(id, name, capacity, personal);
        } else {
            throw new RuntimeException("Tipo de almacén desconocido");
        }
    
        return store;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGrocer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGrocer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGrocer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGrocer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGrocer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGrocer;
    private javax.swing.JTable tblStores;
    private javax.swing.JTextField textCapacity;
    public static javax.swing.JTextField textGrocer;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textPersonal;
    // End of variables declaration//GEN-END:variables
}
