package View;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import controllers.Chofer;
import controllers.Grocer;
import controllers.User;
import controllers.UserCtrl;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Maiki
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form LognView
     */
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        hide = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        textUsername = new javax.swing.JTextField();
        textPassword = new javax.swing.JPasswordField();
        btnExit = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autentificarse");
        setBackground(new java.awt.Color(204, 204, 204));
        setName("Login"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 505));

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(38, 115, 30));
        lblTitle.setText("INICIO DE SESIÓN");
        jPanel2.add(lblTitle);
        lblTitle.setBounds(39, 85, 320, 48);

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(51, 153, 0));
        lblSubtitle.setText("Hola, inicie sesión para acceder");
        jPanel2.add(lblSubtitle);
        lblSubtitle.setBounds(89, 151, 260, 20);

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblUsername.setText("Usuario :");
        jPanel2.add(lblUsername);
        lblUsername.setBounds(24, 246, 59, 18);

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPassword.setText("Contraseña :");
        jPanel2.add(lblPassword);
        lblPassword.setBounds(6, 344, 75, 18);

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/User.png"))); // NOI18N
        jPanel2.add(userIcon);
        userIcon.setBounds(361, 241, 20, 20);

        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/Eye.png"))); // NOI18N
        hide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMouseClicked(evt);
            }
        });
        jPanel2.add(hide);
        hide.setBounds(360, 340, 20, 20);

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/Hide.png"))); // NOI18N
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel2.add(show);
        show.setBounds(360, 340, 20, 20);

        textUsername.setFont(textUsername.getFont().deriveFont(textUsername.getFont().getSize()+2f));
        jPanel2.add(textUsername);
        textUsername.setBounds(90, 240, 260, 30);

        textPassword.setFont(textPassword.getFont().deriveFont(textPassword.getFont().getSize()+2f));
        textPassword.setEchoChar((char)8226);
        textPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(textPassword);
        textPassword.setBounds(90, 340, 260, 30);

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        btnExit.setForeground(new java.awt.Color(38, 115, 30));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        jPanel2.add(btnExit);
        btnExit.setBounds(403, 0, 37, 26);

        btnAccept.setBackground(new java.awt.Color(38, 115, 30));
        btnAccept.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAccept.setForeground(new java.awt.Color(255, 255, 255));
        btnAccept.setText("Acceder");
        btnAccept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAccept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcceptMouseClicked(evt);
            }
        });
        jPanel2.add(btnAccept);
        btnAccept.setBounds(77, 422, 285, 32);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 0, 440, 505));

        setSize(new java.awt.Dimension(835, 505));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
         System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitMouseClicked

    private void hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseClicked
    textPassword.setEchoChar((char)0);
    hide.setVisible(false);
    hide.setEnabled(false);
    show.setVisible(true);
    show.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_hideMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
    textPassword.setEchoChar((char)8226);
    hide.setVisible(true);
    hide.setEnabled(true);
    show.setVisible(false);
    show.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_showMouseClicked

    private void textPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPasswordActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_textPasswordActionPerformed

    private void btnAcceptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptMouseClicked
            if ( !textUsername.getText().equals("") ) {
            if ( !textPassword.getText().equals("") ) {
                UserCtrl ctrl = new UserCtrl();
                try {
                    User usr = ctrl.userExist(textUsername.getText(), textPassword.getText());
                    if (usr != null) {this.setVisible(false);
                        if (usr instanceof Grocer) {
                             FrmGrocer frmGrocer = new FrmGrocer();
                            frmGrocer.setLoginUser(usr);
                            frmGrocer.textGrocer.setText(usr.getUsername().toUpperCase());
                            frmGrocer.setVisible(true);
                            frmGrocer.setLocationRelativeTo(null);
                            
                             } else if (usr instanceof Chofer) {
                            FrmChofer frmChofer = new FrmChofer();
                            frmChofer.setLoginUser(usr);
                            frmChofer.textChofer.setText(usr.getUsername().toUpperCase());
                            frmChofer.setVisible(true);
                            frmChofer.setLocationRelativeTo(null);                                                        
                        } else {
                            FrmUsers frmUser = new FrmUsers();
                            frmUser.setLoginUser(usr);
                            frmUser.setVisible(true);
                            frmUser.setLocationRelativeTo(null);                            
                        }
                            
                             }else {
                        JOptionPane.showMessageDialog(null, "Usuario o contraseña erróneo(a)", "Autentificación", JOptionPane.INFORMATION_MESSAGE);                
                    } } catch (IOException ex) {
                    Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
                 } else {
                JOptionPane.showMessageDialog(null, "Debe escribir la contraseña", "Autentificación", JOptionPane.INFORMATION_MESSAGE);                                
            }
             } else {
            JOptionPane.showMessageDialog(null, "Debe escribir el usuario", "Autentificación", JOptionPane.INFORMATION_MESSAGE);                                            
        }
    }//GEN-LAST:event_btnAcceptMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel hide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel show;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUsername;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}

