/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controllers.Admin;
import controllers.Chofer;
import controllers.Grocer;
import controllers.User;
import controllers.UserCtrl;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FrmUsers extends javax.swing.JFrame {

    /**
     * Creates new form FrmUsers
     */
    
    private User loginUser;
    private ArrayList<User> data;
    private boolean change = false;
    
    public void setLoginUser(User user) {
        this.loginUser = user;
    }
    
    public FrmUsers() {
        initComponents();
        
      DefaultTableModel model = new DefaultTableModel(){
          public boolean isCellEditable(int row, int column) {
                return false;
            }
       };
        model.addColumn("Id");
        model.addColumn("Nombre de Usuario");
        model.addColumn("Contraseña");
        model.addColumn("Rol");
        
        UserCtrl ctrl = new UserCtrl();
        ArrayList<User> arrayUsers = ctrl.getUsers();
        this.data = ctrl.getUsers();

        User usr = null;
        String role = null;
        
         for (int i = 0; i < arrayUsers.size(); i++) {
            usr = arrayUsers.get(i);
            if (usr instanceof Grocer) {
                role = "Almacenero";
            } else if (usr instanceof Chofer) {
                role = "Chofer";
            } else {
                role = "Administrador";
            }

            model.addRow(new Object[]{usr.getId(), usr.getUsername(), usr.getPassword(), role});
        }
         
         usersTable.setModel(model);
        
        usersTable.setFont(new Font("Tahoma", Font.PLAIN, 14));
        usersTable.setRowHeight(30);
        
        int[] arrCol = {40,260,100,100};        
        
          
    }
               

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblRole = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        textPassword = new javax.swing.JTextField();
        textName = new javax.swing.JTextField();
        cmbRole = new javax.swing.JComboBox<>();
        btnEdit = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuarios");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTitle.setText("Por favor, rellene los campos para darle la bienvenida a un nuevo miembro a nuestra gran familia");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(0, 153, 153));

        usersTable.setBackground(new java.awt.Color(0, 153, 153));
        usersTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Contraseña", "Ocupación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usersTable.setGridColor(new java.awt.Color(0, 153, 153));
        usersTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        usersTable.setShowGrid(false);
        usersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usersTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 340, 370));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 30));

        lblRole.setBackground(new java.awt.Color(204, 204, 204));
        lblRole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole.setText("Ocupación :");
        lblRole.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblRole.setOpaque(true);
        getContentPane().add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 90, 30));

        lblName.setBackground(new java.awt.Color(204, 204, 204));
        lblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Nombre de Usuario :");
        lblName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblName.setOpaque(true);
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 30));

        lblPassword.setBackground(new java.awt.Color(204, 204, 204));
        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Contraseña :");
        lblPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblPassword.setOpaque(true);
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 90, 30));

        textPassword.setBackground(new java.awt.Color(204, 204, 204));
        textPassword.setFont(textPassword.getFont().deriveFont(textPassword.getFont().getSize()+2f));
        textPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(textPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 200, 30));

        textName.setBackground(new java.awt.Color(204, 204, 204));
        textName.setFont(textName.getFont().deriveFont(textName.getFont().getSize()+2f));
        textName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(textName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 200, 30));

        cmbRole.setBackground(new java.awt.Color(204, 204, 204));
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Almacenero", "Chofer", "Administrador", " " }));
        cmbRole.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cmbRole.setOpaque(true);
        getContentPane().add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 362, 110, 30));

        btnEdit.setBackground(new java.awt.Color(204, 204, 204));
        btnEdit.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/pencil.png"))); // NOI18N
        btnEdit.setText("Editar");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 90, -1));

        btnNew.setBackground(new java.awt.Color(204, 204, 204));
        btnNew.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/add.png"))); // NOI18N
        btnNew.setText("Agregar");
        btnNew.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNew.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
        });
        getContentPane().add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 90, -1));

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/delete.png"))); // NOI18N
        btnDelete.setText("Eliminar");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 90, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/AlmacenesBanner.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 630, 400));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/disk.png"))); // NOI18N
        btnSave.setText("Guardar");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(204, 204, 204));
        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/door_in.png"))); // NOI18N
        btnClose.setText("Cerrar");
        btnClose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 340, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersTableMouseClicked
         int row = usersTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)usersTable.getModel();
        textName.setText(model.getValueAt(row, 1).toString());
        textPassword.setText(model.getValueAt(row, 2).toString());
        cmbRole.setSelectedItem(model.getValueAt(row, 3).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_usersTableMouseClicked

    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked
        if ( !textName.getText().equals("") && !textPassword.getText().equals("") ) {
            DefaultTableModel model = (DefaultTableModel)usersTable.getModel();        
            String role = null;
            int id = model.getRowCount() + 1;
            switch (cmbRole.getSelectedIndex()) { 
                case 0:
                    role="Almacenero";
                    break;
                case 1:
                    role="Chofer";
                    break;
                case 2:
                    role="Administrador";
                    break;
            }
             model.addRow(new Object[]{id, textName.getText(), textPassword.getText(), role});
            usersTable.setModel(model);
            textName.setText("");
            textPassword.setText("");
            cmbRole.setSelectedIndex(0);
        }// TODO add your handling code here:
        change = true;
    }//GEN-LAST:event_btnNewMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
         int row = usersTable.getSelectedRow();
        if (row >= 0) {
            DefaultTableModel model = (DefaultTableModel)usersTable.getModel();
            model.setValueAt(textName.getText().trim(), row, 1);
            model.setValueAt(textPassword.getText().trim(), row, 2);
            String role = null;
            switch (cmbRole.getSelectedIndex()) {
                case 0:
                    role="Almacenero";
                    break;
                case 1:
                    role="Chofer";
                    break;
                case 2:
                    role="Administrador";
                    break;
            }
            model.setValueAt(role, row, 3);
        }        // TODO add your handling code here:
        change = true;
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        int row = usersTable.getSelectedRow();
        
        if (row >= 0) {
            DefaultTableModel model = (DefaultTableModel)usersTable.getModel();
            
            String id = model.getValueAt(row, 0).toString();
            
            if (!this.loginUser.getId().equals(id)) {
        
                int resp = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar este usuario", "Eliminar usuario", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if(resp == 0) {
                    model.removeRow(row);
                    
                    textName.setText("");
                    textPassword.setText("");
                    cmbRole.setSelectedIndex(0);                    
                }
            
            } else {
                JOptionPane.showMessageDialog(null, "El usuario logueado no se puede eliminar", "Eliminar Usuario", JOptionPane.INFORMATION_MESSAGE);                        
            }
        
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar el usuario que desea eliminar", "Eliminar Usuario", JOptionPane.INFORMATION_MESSAGE);            
        }        // TODO add your handling code here:
        change = true;
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
       if(change){
         int confirm =  JOptionPane.showConfirmDialog(null, "Hay cambios sin guardar, desea salir igualmente?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
         if(confirm == 0){
             FrmLogin frmlogin = new FrmLogin();
        frmlogin.setVisible(true);
        frmlogin.setLocationRelativeTo(null);                                                        
        
        this.dispose();       
         }
       }else{
       FrmLogin frmlogin = new FrmLogin();
        frmlogin.setVisible(true);
        frmlogin.setLocationRelativeTo(null);                                                        
        
        this.dispose(); 
       }
       
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
       
        DefaultTableModel model = (DefaultTableModel)usersTable.getModel();
        ArrayList<User> arrayUsers = new ArrayList<>();

        for (int i=0; i<model.getRowCount(); i++) {                
            switch (model.getValueAt(i, 3).toString()) {
                case "Almacenero":
                    arrayUsers.add(new Grocer(model.getValueAt(i, 0).toString(), model.getValueAt(i, 1).toString(), model.getValueAt(i, 2).toString()));
                    break;
                case "Chofer":
                    arrayUsers.add(new Chofer(model.getValueAt(i, 0).toString(), model.getValueAt(i, 1).toString(), model.getValueAt(i, 2).toString()));
                    break;
                case "Administrador":
                    arrayUsers.add(new Admin(model.getValueAt(i, 0).toString(), model.getValueAt(i, 1).toString(), model.getValueAt(i, 2).toString()));
                    break;
            }
            
        }
        
        UserCtrl ctrl = new UserCtrl();
        boolean isSaved = ctrl.saveUsers(arrayUsers);
        
        if ( isSaved ) {
            JOptionPane.showMessageDialog(null, "Información guardada con éxito", "Usuarios", JOptionPane.INFORMATION_MESSAGE);  
            
   
            
            
        } else {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al guardar los datos", "Usuarios", JOptionPane.ERROR_MESSAGE);                        
        }        // TODO add your handling code here:
        change = false;
    }//GEN-LAST:event_btnSaveMouseClicked

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textPassword;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
